version: '2.1'
services:
  db:
    image: postgres:14.1-alpine
    # restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: legal_acts_db
      APP_DB_NAME: legal_acts_db
      PGDATA: /var/lib/postgresql/data/store/
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./api/db/start:/docker-entrypoint-initdb.d/
      - ./db_data_store:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  fe:
    build:
      context: .
      dockerfile: FE_Dockerfile
    ports:
      - 3000:3000
    depends_on: 
      - api